---
title: "Publications"
toc: true
---

## Journal Articles (Peer-Reviewed)

<ol reversed>
<li>Capitanio, F. A., Gollapalli, T., Munukutla, R., Graciosa, J. C., Zuhair, M., Beall, A., & Dal Zilio, L. (2025). Bridging the gap between subduction dynamics and the long-term strength of megathrusts. <em>Nature Communications</em>. <a href="https://doi.org/10.1038/s41467-025-65824-7">https://doi.org/10.1038/s41467-025-65824-7</a></li>

<li>Moresi, L., Mansour, J., Giordani, J., Knepley, M., Knight, B., Graciosa, J. C., Gollapalli, T., Lu, N., & Beucher, R. (2025). Underworld3: Mathematically self-describing modelling in Python for desktop, HPC and cloud. <em>Journal of Open Source Software</em>. <a href="https://doi.org/10.21105/joss.07831">https://doi.org/10.21105/joss.07831</a></li>

<li>Graciosa, J. C., Capitanio, F. A., Beall, A., Hargreaves, M., Gollapalli, T., Tang, T., & Zuhair, M. (2025). Testing driving mechanisms of megathrust seismicity with explainable artificial intelligence. <em>Journal of Geophysical Research: Solid Earth</em>. <a href="https://doi.org/10.1029/2024JB028774">https://doi.org/10.1029/2024JB028774</a></li>

<li>Zuhair, M., Gollapalli, T., Capitanio, F. A., Betts, P. G., & Graciosa, J. C. (2022). The role of slab step on tectonic loading along subduction zones: Inferences on the seismotectonics of the Sunda convergent margin. <em>Tectonics</em>. <a href="https://doi.org/10.1029/2022TC007242">https://doi.org/10.1029/2022TC007242</a></li>

<li>Ghosh, A., Gollapalli, T., & Steinberger, B. (2017). The importance of upper mantle heterogeneity in generating the Indian Ocean geoid low. <em>Geophysical Research Letters</em>. <a href="https://doi.org/10.1002/2017GL075392">https://doi.org/10.1002/2017GL075392</a></li>
</ol>

## Working Papers & Papers Under Review

1. Khalil, H., Gollapalli, T., Capitanio, F. A., Knight, B., & Brune, S. How far-field rotational motion drives rift evolution. *Earth and Planetary Science Letters*. Submitted.

## My Thesis

1. Gollapalli, T. (2022). *Unravelling tectonic coupling and loading along Sunda margin through 3-D regional numerical modelling*. Doctoral thesis, Monash University and Indian Institute of Technology Bombay.

## Reports

Reports will be added here as they become publicly available.

## Github Repos with DOI

1. Underworld3: <https://github.com/underworldcode/underworld3>  
   Software archive DOI: <https://doi.org/10.5281/zenodo.16812088>

## Media Coverage

<ol reversed>
<li>Hargreaves, M. (2022). Unlocking the secrets of great earthquakes with deep learning. <em>Monash DeepNeuron</em>. <a href="https://deepneuron.org/blogs/8r20f2vr3vn05h9fuao62tj7anhr39">https://deepneuron.org/blogs/8r20f2vr3vn05h9fuao62tj7anhr39</a></li>

<li>Gollapalli, T. (2020). Advanced geodynamic models of giant earthquakes. <em>European Geosciences Union Geodynamics Blog</em>. <a href="https://blogs.egu.eu/divisions/gd/2020/09/16/giant-earthquakes/">https://blogs.egu.eu/divisions/gd/2020/09/16/giant-earthquakes/</a></li>
</ol>
